const optimizeImage = (url) =>
  url.replace("/upload/", "/upload/q_auto,f_auto/");

export const FILTERS = [
  { name: "all", active: true },
  { name: "watercolor", active: false },
  { name: "ink", active: false },
  { name: "cover", active: false },
  { name: "environment", active: false },
  { name: "character", active: false },
];

export const IMAGES = [
  {
    id: 1,
    title: "Man looking at grave",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775234219/1_qttkmw.png"),
    medium: "pencil",
    category: ["character"],
  },
  {
    id: 2,
    title: "Astronaut",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775234220/2_hyshmk.png"),
    medium: "color",
    category: ["character", "cover", "ink"],
  },
  {
    id: 3,
    title: "Frozen Discovery",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775234219/3_l7v1zk.png"),
    medium: "digital",
    category: ["character", "environment"],
  },
  {
    id: 4,
    title: "Tifa",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775234219/4_bkpnhq.png"),
    medium: "watercolor",
    category: ["character", "watercolor"],
  },
  {
    id: 5,
    title: "President",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236669/5_ws6eop.png"),
    medium: "ink",
    category: ["character", "cover"],
  },
  {
    id: 6,
    title: "Big man",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236669/6_rwwopv.png"),
    medium: "watercolor",
    category: ["character"],
  },
  {
    id: 7,
    title: "Orange monster",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775238450/7_ocujoz.png"),
    medium: "watercolor",
    category: ["character", "ink"],
  },
  {
    id: 8,
    title: "Espinazo cover",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775238450/8_xff4df.png"),
    medium: "watercolor",
    category: ["cover", "environment"],
  },
  {
    id: 9,
    title: "Woman face",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236670/9_l8mgli.png"),
    medium: "watercolor",
    category: ["character", "watercolor"],
  },
  {
    id: 10,
    title: "monster",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236670/10_z2yai0.png"),
    medium: "watercolor",
    category: ["character", "ink"],
  },
  {
    id: 11,
    title: "Among us",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236670/11_vzle3r.png"),
    medium: "watercolor",
    category: ["cover", "environment"],
  },
  {
    id: 12,
    title: "Superhero",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236670/12_gv55jt.png"),
    medium: "watercolor",
    category: ["character", "ink"],
  },
  {
    id: 13,
    title: "Friends",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/13_uukzve.png"),
    medium: "watercolor",
    category: ["ink"],
  },
  {
    id: 14,
    title: "Viking",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/14_c3agxy.png"),
    medium: "watercolor",
    category: ["character", "watercolor"],
  },
  {
    id: 15,
    title: "Ship",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/15_bqvxvo.png"),
    medium: "watercolor",
    category: ["ink"],
  },
  {
    id: 16,
    title: "Sweat girl",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/16_mocbag.png"),
    medium: "watercolor",
    category: ["character", "watercolor"],
  },
  {
    id: 17,
    title: "Werewolf",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/17_gtaztm.png"),
    medium: "watercolor",
    category: ["character"],
  },
  {
    id: 18,
    title: "Player",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/18_kqfsac.png"),
    medium: "watercolor",
    category: ["character", "watercolor"],
  },
  {
    id: 19,
    title: "Frankenstein",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/19_vik8is.png"),
    medium: "watercolor",
    category: ["character", "ink"],
  },
  {
    id: 20,
    title: "Monster",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775236671/20_tc3zid.png"),
    medium: "watercolor",
    category: ["character", "ink"],
  },
  {
    id: 21,
    title: "Bride",
    image: optimizeImage("https://res.cloudinary.com/dmig1qslw/image/upload/v1775239495/21_d9bhai.png"),
    medium: "watercolor",
    category: ["character", "ink"],
  },
];
